interface IWeatherHourResponse {
  response: {
    header: {
      resultCode: string;
      resultMsg: string;
    };
    body: {
      pageNo: number;
      numOfRows: number;
      totalCount: number;
      items: {
        item: {
          stnId: string;
          stnNm: string;
          tm: string;
          avgTa: string;
          minTa: string;
          minTaHrmt: string;
          maxTa: string;
          maxTaHrmt: string;
          mi10MaxRn: string;
          mi10MaxRnHrmt: string;
          hr1MaxRn: string;
          hr1MaxRnHrmt: string;
          sumRnDur: string;
          sumRn: string;
          maxInsWs: string;
          maxInsWsWd: string;
          maxInsWsHrmt: string;
          maxWs: string;
          maxWsWd: string;
          maxWsHrmt: string;
          avgWs: string;
          hr24SumRws: string;
          maxWd: string;
          avgTd: string;
          minRhm: string;
          minRhmHrmt: string;
          avgRhm: string;
          avgPv: string;
          avgPa: string;
          maxPs: string;
          maxPsHrmt: string;
          minPs: string;
          minPsHrmt: string;
          avgPs: string;
          ssDur: string;
          sumSsHr: string;
          hr1MaxIcsrHrmt: string;
          hr1MaxIcsr: string;
          sumGsr: string;
          ddMefs: string;
          ddMefsHrmt: string;
          ddMes: string;
          ddMesHrmt: string;
          sumDpthFhsc: string;
          avgTca: string;
          avgLmac: string;
          avgTs: string;
          minTg: string;
          avgCm5Te: string;
          avgCm10Te: string;
          avgCm20Te: string;
          avgCm30Te: string;
          avgM05Te: string;
          avgM10Te: string;
          avgM15Te: string;
          avgM30Te: string;
          avgM50Te: string;
          sumLrgEv: string;
          sumSmlEv: string;
          n99Rn: string;
          iscs: string;
          sumFogDur: string;
        }[];
      };
    };
  };
}
