version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
hooks:
  BeforeInstall:
    - location: agent/clear.sh
      timeout: 180
  AfterInstall:
    - location: agent/execute.sh
      timeout: 180
