import { ICityGeolocation } from "../interface";

export const cityEngToKorDictionary = {
  seoul: "서울",
  chungbuk: "충북",
  busan: "부산",
  chungnam: "충남",
  daegu: "대구",
  daejeon: "대전",
  gangwon: "강원",
  gwangju: "광주",
  gyeongbuk: "경북",
  gyeonggi: "경기",
  gyeongnam: "경남",
  incheon: "인천",
  jeju: "제주",
  jeonbuk: "전북",
  jeonnam: "전남",
  sejong: "세종",
  ulsan: "울산",
};

export const cityGeolocationList: ICityGeolocation[] = [
  { city: "서울", nx: 60, ny: 127 },
  { city: "강원", nx: 73, ny: 134 },
  { city: "경기", nx: 60, ny: 120 },
  { city: "경남", nx: 91, ny: 77 },
  { city: "경북", nx: 89, ny: 91 },
  { city: "광주", nx: 58, ny: 74 },
  { city: "대구", nx: 89, ny: 90 },
  { city: "대전", nx: 67, ny: 100 },
  { city: "부산", nx: 98, ny: 76 },
  { city: "세종", nx: 66, ny: 103 },
  { city: "울산", nx: 102, ny: 84 },
  { city: "인천", nx: 55, ny: 124 },
  { city: "전남", nx: 51, ny: 67 },
  { city: "전북", nx: 63, ny: 89 },
  { city: "제주", nx: 52, ny: 38 },
  { city: "충남", nx: 68, ny: 100 },
  { city: "충북", nx: 69, ny: 107 },
];

export const cityCollectionList: ICityGeolocation[] = [
  { city: "서울", stn: 108 },
  { city: "강원", stn: 93 },
  { city: "경기", stn: 119 },
  { city: "경남", stn: 155 },
  { city: "경북", stn: 138 },
  { city: "광주", stn: 156 },
  { city: "대구", stn: 143 },
  { city: "대전", stn: 133 },
  { city: "부산", stn: 159 },
  { city: "세종", stn: 239 },
  { city: "울산", stn: 152 },
  { city: "인천", stn: 112 },
  { city: "전남", stn: 168 },
  { city: "전북", stn: 146 },
  { city: "제주", stn: 184 },
  { city: "충남", stn: 232 },
  { city: "충북", stn: 131 },
];

export const cityToAbbreviation = {
  서울특별시: "서울",
  부산광역시: "부산",
  대구광역시: "대구",
  인천광역시: "인천",
  광주광역시: "광주",
  대전광역시: "대전",
  울산광역시: "울산",
  세종특별자치시: "세종",
  경기도: "경기",
  강원도: "강원",
  충청북도: "충북",
  충청남도: "충남",
  전라북도: "전북",
  전라남도: "전남",
  경상북도: "경북",
  경상남도: "경남",
  제주특별자치도: "제주",
};

export const cityFromAbbreviation = {
  서울: "서울특별시",
  부산: "부산광역시",
  대구: "대구광역시",
  인천: "인천광역시",
  광주: "광주광역시",
  대전: "대전광역시",
  울산: "울산광역시",
  세종: "세종특별자치시",
  경기: "경기도",
  강원: "강원도",
  충북: "충청북도",
  충남: "충청남도",
  전북: "전라북도",
  전남: "전라남도",
  경북: "경상북도",
  경남: "경상남도",
  제주: "제주특별자치도",
};
