name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Make zip file
        run: zip -r deploy *
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://raccoon-weather-server

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name raccoon-weather-server \
          --deployment-group-name raccoon-weather-server-deploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=raccoon-weather-server,key=deploy.zip,bundleType=zip
